ORACLE CREDENTIALS
------------------

DATABASE USERID: lab1btrg30@ORCL11G
DATABASE PASSWORD: lab1boracle 



ORACLE QUERIES
--------------

Users Table: 
CREATE TABLE USERS
(
	USERNAME  VARCHAR2(20) PRIMARY KEY,
	PASSWORD  VARCHAR2(20),
	ROLE      VARCHAR2(10),
	MOBILE_NO NUMBER(10)
);

Airports Table:
CREATE TABLE AIRPORTS
(
	AIRPORTNAME  VARCHAR2(20) PRIMARY KEY,
	ABBREVIATION VARCHAR2(5),
	LOCATION     VARCHAR2(40)
);

Flights Information Table:
CREATE TABLE FLIGHTS
(
	FLIGHT_NO     VARCHAR2(5) PRIMARY KEY,
	AIRLINE       VARCHAR2(10),
	DEPCITY       VARCHAR2(10),
	ARRCITY       VARCHAR2(10),
	DEPDATE       DATE,
	ARRDATE       DATE,
	DEPTIME       NUMBER(8),
	ARRTIME       NUMBER(8),
	FIRSTSEATS    NUMBER(6),
	FIRSTSEATFARE NUMBER(8,2),
	BUSSSEATS     NUMBER(6),
	BUSSSEATSFARE NUMBER(6,2)
);

Bookings Table:
CREATE TABLE BOOKINGS
(
	BOOKING_ID       VARCHAR2(5) PRIMARY KEY,
	FLIGHT_NO        REFERENCES FLIGHTS.FLIGHT_NO,
	CUST_EMAIL       VARCHAR2(30),
	NO_OF_PASSENGERS NUMBER(3),
	CLASS_TYPE       VARCHAR2(10),
	TOTAL_FARE       NUMBER(6,2),
	SEAT_NUMBER      NUMBER(3),
	CREDITCARD_INFO  VARCHAR2(16),
	SRC_CITY         VARCHAR2(10),
	DEST_CITY        VARCHAR2(10)
);
