ORACLE CREDENTIALS
------------------

DATABASE USERID: lab1btrg30@ORCL11G
DATABASE PASSWORD: lab1boracle 



ORACLE QUERIES
--------------

Users Table: 
CREATE TABLE USERS
(
	USERNAME  VARCHAR2(40) PRIMARY KEY,
	PASSWORD  VARCHAR2(100),
	EMAIL     VARCHAR2(40),
	ROLE      VARCHAR2(20),
	MOBILE_NO VARCHAR2(30)
);

Airports Table:
CREATE TABLE AIRPORTS
(
	AIRPORTNAME  VARCHAR2(40),
	ABBREVIATION VARCHAR2(10) PRIMARY KEY,
	LOCATION     VARCHAR2(40)
);

Flights Information Table:
CREATE TABLE FLIGHTS
(
	FLIGHT_NO     VARCHAR2(20) PRIMARY KEY,
	AIRLINE       VARCHAR2(40),
	DEP_CITY      VARCHAR2(40),
	ARR_CITY      VARCHAR2(40),
	DEP_DATE      DATE,
	ARR_DATE      DATE,
	DEP_TIME      DATE,
	ARR_TIME      DATE,
	FIRSTSEATS    NUMBER(6),
	FIRSTSEATFARE NUMBER(10,2),
	BUSSSEATS     NUMBER(6),
	BUSSSEATSFARE NUMBER(10,2),
	DEP_AIRPORT   VARCHAR2(10) REFERENCES AIRPORTS(ABBREVIATION),
	ARR_AIRPORT   VARCHAR2(10) REFERENCES AIRPORTS(ABBREVIATION),
	VERSION       NUMBER(10)
);

Bookings Table:
CREATE TABLE BOOKINGS
(
	BOOKING_ID       VARCHAR2(20) PRIMARY KEY,
	FLIGHT_NO        REFERENCES FLIGHTS(FLIGHT_NO),
	USERNAME         VARCHAR2(40) REFERENCES USERS(USERNAME),
	NO_OF_PASSENGERS NUMBER(3),
	CLASS_TYPE       VARCHAR2(10),
	TOTAL_FARE       NUMBER(16,2),
	SEAT_NUMBER      VARCHAR2(20),
	CREDITCARD_INFO  VARCHAR2(20),
	SRC_CITY         VARCHAR2(40),
	DEST_CITY        VARCHAR2(40)
);

Bookings Sequence:
CREATE    SEQUENCE BOOKING_SEQUENCE
START     WITH     1000
INCREMENT BY       1;